---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:

  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .

  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: macos
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.tgz
            *.zip
